prometheus:
  install_dir: /opt
  rules:
  server:
    enable: False
    version: 2.5.0
    external_url:
    source:
    option:
      retention_time: 15d
    config:
      global:
        scrape_interval: 15s
        evaluation_interval: 15s
      alerting:
        alertmanagers:
          - static_configs:
            - targets:
      rule_files:
      scrape_configs:
        - job_name: 'prometheus'
          static_configs:
            - targets: ['localhost:9090']
  alertmanager:
    enable: False
    version: 0.16.0-alpha.0
    config:
      global:
        smtp_smarthost: 'localhost:25'
        smtp_from: 'noreply@alertmanager.com'
        resolve_timeout: 5m
      route:
        group_by: ['alertname']
        group_wait: 10s
        group_interval: 10s
        repeat_interval: 1h
        receiver: 'web.hook'
      receivers:
        - name: 'web.hook'
          webhook_configs:
            - url: 'http://127.0.0.1:5001/'
      inhibit_rules:
        - source_match:
            severity: 'critical'
          target_match:
            severity: 'warning'
          equal: ['alertname', 'dev', 'instance']
  node_exporter:
    enable: False
    version: 0.17.0-rc.0
    source:
  snmp_exporter:
    enable: False
    version: 0.13.0
    source:
